### ISSUE TITLE
[User Story 9] Search Specific to Categories

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#176]
### Search Specific to Categories

| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| Medium | Medium | **8** |

As a user I should be able to specify a search relative to a category. If i'm browsing through a *category page* I should be able to type a search in and the results should relevant to my input + the category page I was on.

- [x] 5.1 Create breadcrumbs on search page #182 (**2.5  Hours**) 
- [x] 5.2 Modify routes search takes to display results #181 (**3.5 Hours**) 
- [x] 5.3 Modify scout/algolia to take in product categories  #180 (**3 Hours**)  

#### Total: **9 Hours**

**Comment by laurie-y** [comment]
## Acceptance Test
![us9](https://user-images.githubusercontent.com/31772505/32358906-01f658c2-c020-11e7-8051-0f498a35d2bf.PNG)
