### ISSUE TITLE
[User Story 11] Pagination

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#177]
## User Story Title

| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| Low | High | **8** |

As a user when I visit classifiedz.xyz I should be able to browse through the entire list of products available on the website. Not only the 25 displayed on the homepage. 

- [X] 4.1 Create pagination buttons #89  (**1 Hours**)   
- [x] 4.2 Generate the appropriate number of buttons once a page is loaded #89 (**2 Hours**)   
- [x] 4.3 Generate the appropriate number of ads per page #89 (**3 Hours**)   

#### Total: **6 Hours**

**Comment by laurie-y** [comment]
## Acceptance Test
![us11](https://user-images.githubusercontent.com/31772505/32357523-ed448090-c013-11e7-9d37-1e21ce63e18d.PNG)
