### ISSUE TITLE
[User Story 10] User & Seller Reviews

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#178]
### User & Seller Reviews

| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| Medium | High | **8** |

As a user(buyer) I would like to be able to see a sellers reviews. As a user(seller) I would like to be able to see the a possible buyers reviews before further arrangements are made to sell an item. Reviews should be on a scale of 1-5 and should display as an average on the Store Page #161.

- [x] 3.1 Create new row in the database, under the user table for reviews #123 (**2.5 Hours**) 
- [x] 3.2 Create HTML and CSS to display the 5 stars on a user profile  or seller page #123 (**2.5 Hours**) 
- [x] 3.3 Get the data from the database and display it #123 (**1 Hours**)   
#### Total: **6 Hours**

**Comment by kevcamel** [comment]
@Swallow666 @laurie-y @HanGao2333 @rami186 @BrandonBalala @neqqash @monnyy 
(thumbs up thumbs down) || (5 star ratings) ??

**Comment by laurie-y** [comment]
Depends on how precise we want our ratings to be. I think if we do it with stars, people should also be able to justify why they gave that rating. Otherwise thumbs up or down is pretty black and white and doesn't really need much else.

**Comment by rami186** [comment]
I'm working on thumbs up and thumbs down for now

**Comment by Swallow666** [comment]
@kcamcam  thumbs up and thumbs down is a great idea because it does not need buyers to consider how many stars to give, and stars = precise

**Comment by laurie-y** [comment]
I think this would be more accurately described as user reviews since we're not distinguishing sellers from buyers. Their store will display the experience they've had with other users whether as a buyer or a seller (as reviewed by the users they've interacted with). Am I making sense?

**Comment by kevcamel** [comment]
thumbs up/down is a good idea, then we can just display a %.
ex:
Seller Ricky Bobbys Page would show:
77% 👍 33% 👎 (203 reviews)

**Comment by kevcamel** [comment]
@rami186  you should have issues created for each task, so that you can reference them when you commit.
Ex:
we should have an issue called:  
- 3.1 Create new row in the database, under the user table for reviews #000 (2.5 Hours)  

then when you commit your message should be:
- "Created a row in the database to store values of ratings, resolves #000"

**Comment by kevcamel** [comment]
Acceptance testing has been done, the US can be closed.
<img width="735" alt="screen shot 2017-11-16 at 10 48 14 pm" src="https://user-images.githubusercontent.com/16027312/32928524-49d95ab2-cb20-11e7-8b0a-cee9bc34218a.png">
