### ISSUE TITLE
[User Story 18] Hide Disqus

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#196]
### Hide Disqus

| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| High | Low | **3** |

As a a User when creating or editing an ad I should have the choice of showing or hiding the chat under my ad.

- [ ] 18.1 Create a new row in the database for show/hide chat #201 (**1 hours**)
- [ ] 18.2 Create check box in create and edit forms to show/hide disqus  #202 (**0.5 Hours**) 
- [ ] 18.3 Change ad page to check for a boolean to show/hide(not show) chat on an ad  #203 (**1 Hours**) 

#### Total: **2.5 Hours**

**Comment by kevcamel** [comment]
<img width="718" alt="screen shot 2017-11-07 at 11 21 57 pm" src="https://user-images.githubusercontent.com/16027312/32531569-78bcf538-c412-11e7-9011-0fa59431645d.png">
