### ISSUE TITLE
[User Story 5] Categories and Sub-Categories

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#50]
I want the system to allow any user to browse classified items with ease. I believe that creating a hierarchy of categories and subcategories can solve this. A proper hierarchy should have more than 2 levels. For example, i like "Keyboards", there should be a sub category of items under a main category, which could be named something like "musical instruments". However, there a are many sorts of guitars which should be separated to facilitate browsing like "wired keyboards" and "wireless keyboards".  

- [x]  Create First Tier Categories #68 
- [x]  Create Second Tier Categories  #69 
- [x]  Create Third Tier Categories  #70 

**Estimated Hours:** 4 hours  
**Risk:** MEDIUM  
**Priority:** HIGH  
### Story points: 3

**Comment by laurie-y** [comment]
## Acceptance Test
![us5](https://user-images.githubusercontent.com/31772505/32358741-dbbe2b40-c01e-11e7-8925-c87f262a7c65.PNG)
