### ISSUE TITLE
[User Story 8] Edit profile page 

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#71]
### User Profile Page

| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| Low | High | **8** |

As a user, I should be able to access my own profile page as well as other peoples profile page. When other users view someone else's profile, the profile page should contain general information about the user as well as all of their ads that they've posted and are still active. When a user views their own profile page, they should have the option to edit the information shown. The user should also be able to view all of their valid ads and delete ads that are no longer valid.

#### Front-end
- [x] Profile page #73  (**1 Hours**) 
- [x] General Information #74 (**0.5 Hours**) 
- [x] Form for changing information #75 (**1 Hours**) 
- [x] Active Ads #76 (**1 Hours**) 
- [x] Option to delete ads #77 (**1 Hours**) 

#### Back-end
- [x] Accessible through navbar #78 (**1 Hours**) 
- [x] Ads specific to user appear in profile page #79 (**2 Hours**) 
- [x] Functioning edit form #80 (**2 Hours**) 
  
#### Total: **9.5 Hours**

**Comment by Swallow666** [comment]
task #76 #77 #79 , we move it to Your store user story in sprint 4 since we have some new ideas.

**Comment by laurie-y** [comment]
## Acceptance Test
![us8](https://user-images.githubusercontent.com/31772505/32359415-4e75af3c-c024-11e7-89b1-84db0b20a82a.PNG)
