### ISSUE TITLE
[User Story7] Functioning search bar

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#81]
### Functioning Search Bar
| Risk | Priority | Story Points |
| :---: | :---: | :---: |
| Medium | High | **8** |

As a user I should be able to search directly from the navigation bar. Searching should be able to bring up specific ads that are either matched by the title, the description, the category, etc.

#### Back End:
- [x] Create a Regex to check input for all or part of the search #113 (**1 hours**)
- [x] Create a function to search the database for title, description, title, category #113 (**3 hours**)
- [x] Return Results #113 (**2 hours**)
- [x] Option to refine results (do a more specific search) #125 (**2 hours**)

#### Front End
- [x] Create a page to display the results of the search #123 (**1 hours**)
- [x] Create options to refine results #122 (**1 hours**)
#### Total Hours: **10 hours**

**Comment by kevcamel** [comment]
@BrandonBalala @neqqash can you confirm the issue #'s for the tasks I added up top, I think they mostly belong to #113.

**Comment by laurie-y** [comment]
## Acceptance Test
![us7](https://user-images.githubusercontent.com/31772505/32359472-ba4cb87c-c024-11e7-9cf3-cf2a4e6ec343.PNG)
