### ISSUE TITLE
[User Story 4] Post Ad Page

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#9]
## Create a post ad page

Users should should be able to create and ad post where all the details of their item can be given. The ad should appear on the main page once submitted. Users should also be able to access this option from the navbar.

- [x] Post ad page template #37 
- [x] Input  fields for title #38 
- [x] Input  fields for description  #39 
- [x] Category specification #40 
- [x] Upload image button  #41 
- [x] Contact preference #42 
- [x] Price input #43 
- [x] Submit/Cancel buttons  #44 
- [x] Have the ads posted to the front page #45 
- [x] Gain access to the page through the navbar #46  
- [x] Functional image upload #52   
  
**Estimated Hours:** 6 hours  
**Risk:** MEDIUM  
**Priority:** HIGH  
### Story points: 8

**Comment by laurie-y** [comment]
## Acceptance Test
![us4](https://user-images.githubusercontent.com/31772505/32358483-d820b928-c01c-11e7-951f-2fcb85693455.PNG)
